const saludo = "Hola, empezamos con el primer proyecto"
const saludo = "Vamos a ver si entendemos un poco"
const saludo = "Ojala pronto agarremos cancha"
const saludo = "Creo que ya entendi como subir un mensaje"
const saludo = "Mensaje para Mai"
const saludo = "Vamos a poder con esto"
const saludo = "Y con mucho más"
